switch from sklearn IncrementalPCA to PCA
On our cluster, IncrementalPCA was giving the following error message
for large expression matrices:

ValueError: Too large work array required -- computation cannot be
performed with standard 32-bit LAPACK.

PCA works just fine as long as enough memory is available. Usage of
IncrementalPCA could be revisited.